# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calendar/v1/calendar.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'calendar/v1/calendar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import event_pb2 as common_dot_v1_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63\x61lendar/v1/calendar.proto\x12\x0b\x63\x61lendar.v1\x1a\x15\x63ommon/v1/event.proto\"\x8f\x02\n\x13\x43\x61lendarSyncRequest\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x16.common.v1.EventHeaderR\x06header\x12\x17\n\x07user_id\x18\x02 \x01(\tR\x06userId\x12\x12\n\x04year\x18\x03 \x01(\x05R\x04year\x12\x1f\n\x0bweek_number\x18\x04 \x01(\x05R\nweekNumber\x12*\n\x11\x66orce_full_resync\x18\x05 \x01(\x08R\x0f\x66orceFullResync\x12(\n\x10\x64\x61te_range_start\x18\x06 \x01(\tR\x0e\x64\x61teRangeStart\x12$\n\x0e\x64\x61te_range_end\x18\x07 \x01(\tR\x0c\x64\x61teRangeEnd\"\x8a\x02\n\x0b\x43ourseEvent\x12\x1f\n\x0b\x65xternal_id\x18\x01 \x01(\tR\nexternalId\x12)\n\x10\x64\x65terministic_id\x18\x02 \x01(\tR\x0f\x64\x65terministicId\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12 \n\x0b\x64\x65scription\x18\x04 \x01(\tR\x0b\x64\x65scription\x12\x1a\n\x08location\x18\x05 \x01(\tR\x08location\x12\"\n\rstart_time_ms\x18\x06 \x01(\x03R\x0bstartTimeMs\x12\x1e\n\x0b\x65nd_time_ms\x18\x07 \x01(\x03R\tendTimeMs\x12\x17\n\x07is_exam\x18\x08 \x01(\x08R\x06isExam\"\xa5\x02\n\x12\x43\x61lendarSyncResult\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x16.common.v1.EventHeaderR\x06header\x12!\n\x0ctotal_events\x18\x02 \x01(\x05R\x0btotalEvents\x12\'\n\x0finserted_events\x18\x03 \x01(\x05R\x0einsertedEvents\x12%\n\x0eupdated_events\x18\x04 \x01(\x05R\rupdatedEvents\x12?\n\x0eupcoming_exams\x18\x05 \x03(\x0b\x32\x18.calendar.v1.CourseEventR\rupcomingExams\x12+\n\x11\x63onflict_severity\x18\x06 \x01(\tR\x10\x63onflictSeverityBVZTgithub.com/VictorAgahi/hermes-core/workers-business/pkg/proto/calendar/v1;calendarv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calendar.v1.calendar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZTgithub.com/VictorAgahi/hermes-core/workers-business/pkg/proto/calendar/v1;calendarv1'
  _globals['_CALENDARSYNCREQUEST']._serialized_start=67
  _globals['_CALENDARSYNCREQUEST']._serialized_end=338
  _globals['_COURSEEVENT']._serialized_start=341
  _globals['_COURSEEVENT']._serialized_end=607
  _globals['_CALENDARSYNCRESULT']._serialized_start=610
  _globals['_CALENDARSYNCRESULT']._serialized_end=903
# @@protoc_insertion_point(module_scope)
