# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/event.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'common/v1/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/v1/event.proto\x12\tcommon.v1\"\xa6\x02\n\x0b\x45ventHeader\x12\x19\n\x08\x65vent_id\x18\x01 \x01(\tR\x07\x65ventId\x12\x19\n\x08trace_id\x18\x02 \x01(\tR\x07traceId\x12\'\n\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12%\n\x0eorigin_service\x18\x04 \x01(\tR\roriginService\x12\x1c\n\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12-\n\x06status\x18\x06 \x01(\x0e\x32\x15.common.v1.TaskStatusR\x06status\x12\x1f\n\x0bretry_count\x18\x07 \x01(\x05R\nretryCount\x12#\n\rtarget_worker\x18\x08 \x01(\tR\x0ctargetWorker*\x9a\x02\n\nTaskStatus\x12\x1b\n\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x17\n\x13TASK_STATUS_PENDING\x10\x01\x12\x17\n\x13TASK_STATUS_RUNNING\x10\x02\x12%\n!TASK_STATUS_WAITING_USER_APPROVAL\x10\x03\x12\x18\n\x14TASK_STATUS_APPROVED\x10\x04\x12\x18\n\x14TASK_STATUS_REJECTED\x10\x05\x12\x17\n\x13TASK_STATUS_SUCCESS\x10\x06\x12\x16\n\x12TASK_STATUS_FAILED\x10\x07\x12\x17\n\x13TASK_STATUS_EXPIRED\x10\x08\x12\x18\n\x14TASK_STATUS_RETRYING\x10\tBRZPgithub.com/VictorAgahi/hermes-core/workers-business/pkg/proto/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/VictorAgahi/hermes-core/workers-business/pkg/proto/common/v1;commonv1'
  _globals['_TASKSTATUS']._serialized_start=334
  _globals['_TASKSTATUS']._serialized_end=616
  _globals['_EVENTHEADER']._serialized_start=37
  _globals['_EVENTHEADER']._serialized_end=331
# @@protoc_insertion_point(module_scope)
