# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/task.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'common/v1/task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import event_pb2 as common_dot_v1_dot_event__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ommon/v1/task.proto\x12\tcommon.v1\x1a\x15\x63ommon/v1/event.proto\"}\n\x0bTaskRequest\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x16.common.v1.EventHeaderR\x06header\x12\x1b\n\ttask_type\x18\x02 \x01(\tR\x08taskType\x12!\n\x0cpayload_json\x18\x03 \x01(\tR\x0bpayloadJson\"\x9e\x01\n\x0cTaskResponse\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x16.common.v1.EventHeaderR\x06header\x12\x18\n\x07success\x18\x02 \x01(\x08R\x07success\x12\x1f\n\x0bresult_json\x18\x03 \x01(\tR\nresultJson\x12#\n\rerror_message\x18\x04 \x01(\tR\x0c\x65rrorMessage\"\x87\x02\n\rHITLChallenge\x12.\n\x06header\x18\x01 \x01(\x0b\x32\x16.common.v1.EventHeaderR\x06header\x12\"\n\rshort_task_id\x18\x02 \x01(\tR\x0bshortTaskId\x12\x14\n\x05title\x18\x03 \x01(\tR\x05title\x12 \n\x0b\x64\x65scription\x18\x04 \x01(\tR\x0b\x64\x65scription\x12\'\n\x0fscreenshot_path\x18\x05 \x01(\tR\x0escreenshotPath\x12\'\n\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x12\x18\n\x07\x61\x63tions\x18\x07 \x03(\tR\x07\x61\x63tionsBRZPgithub.com/VictorAgahi/hermes-core/workers-business/pkg/proto/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/VictorAgahi/hermes-core/workers-business/pkg/proto/common/v1;commonv1'
  _globals['_TASKREQUEST']._serialized_start=58
  _globals['_TASKREQUEST']._serialized_end=183
  _globals['_TASKRESPONSE']._serialized_start=186
  _globals['_TASKRESPONSE']._serialized_end=344
  _globals['_HITLCHALLENGE']._serialized_start=347
  _globals['_HITLCHALLENGE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
